'use client';

import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { DESKTOP_INSTALLER_FILENAME, DESKTOP_INSTALLER_PATH, DESKTOP_VERSION } from '@/lib/desktop-release';

type Profile={name:string;email:string;role:string}; type Task={id:string;title:string;status:string;priority:string;project:{name:string}|null}; type Request={id:string;status:string;startAt:string;endAt:string;note:string}; type Session={id:string;startedAt:string;endedAt:string|null;activeSeconds:number;idleSeconds:number;breakSeconds:number;reviewRequired:boolean};
const duration=(seconds:number)=>`${Math.floor(seconds/3600)}h ${Math.floor(seconds%3600/60)}m`;

export default function EmployeePage(){
 const router=useRouter();const [profile,setProfile]=useState<Profile|null>(null);const [tasks,setTasks]=useState<Task[]>([]);const [requests,setRequests]=useState<Request[]>([]);const [sessions,setSessions]=useState<Session[]>([]);const [startAt,setStartAt]=useState('');const [endAt,setEndAt]=useState('');const [note,setNote]=useState('');const [taskId,setTaskId]=useState('');const [message,setMessage]=useState('');
 const load=useCallback(async()=>{const [meResponse,opsResponse]=await Promise.all([fetch('/api/auth/me',{cache:'no-store'}),fetch('/api/employee/operations',{cache:'no-store'})]);const me=await meResponse.json();const ops=await opsResponse.json();if(!meResponse.ok||me.user?.role!=='EMPLOYEE')return router.replace('/login');setProfile(me.user);if(opsResponse.ok){setTasks(ops.tasks||[]);setRequests(ops.requests||[]);setSessions(ops.sessions||[]);}},[router]);
 useEffect(()=>{load();},[load]);
 const totals=useMemo(()=>sessions.reduce((acc,item)=>({active:acc.active+item.activeSeconds,idle:acc.idle+item.idleSeconds,breaks:acc.breaks+item.breakSeconds}),{active:0,idle:0,breaks:0}),[sessions]);
 const submit=async(event:FormEvent)=>{event.preventDefault();const response=await fetch('/api/employee/operations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'REQUEST_MANUAL_TIME',startAt,endAt,note,taskId})});const data=await response.json();setMessage(response.ok?'Manual time request submitted for review.':data.error||'Request failed');if(response.ok){setNote('');await load();}};
 const updateTask=async(id:string,status:string)=>{await fetch('/api/employee/operations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'UPDATE_TASK_STATUS',id,status})});await load();};
 const logout=async()=>{await fetch('/api/auth/logout',{method:'POST'});router.replace('/login');};
 return <main className="min-h-screen bg-[#f5fbfd] text-[#041f24] p-4 md:p-8"><div className="max-w-6xl mx-auto space-y-6"><header className="flex justify-between items-center"><div><img src="/Logo.svg" alt="KR Tasker" className="h-9 object-contain mb-2"/><h1 className="text-xl font-bold">Welcome, {profile?.name||'Employee'}</h1><p className="text-xs text-[#6f797c]">Your time, assignments, corrections and review status</p></div><div className="flex gap-2"><a href={DESKTOP_INSTALLER_PATH} download={DESKTOP_INSTALLER_FILENAME} className="kr-btn-primary text-xs">Download installer v{DESKTOP_VERSION}</a><button onClick={logout} className="kr-btn-secondary text-xs">Sign out</button></div></header>
 <div className="grid grid-cols-3 gap-4">{[['Active today',duration(totals.active)],['Idle today',duration(totals.idle)],['Break today',duration(totals.breaks)]].map(([label,value])=><div key={label} className="kr-card p-5"><span className="text-xs uppercase text-[#6f797c] font-semibold">{label}</span><p className="text-2xl font-extrabold text-[#005766] mt-1">{value}</p></div>)}</div>
 <div className="grid lg:grid-cols-2 gap-5"><section className="kr-card overflow-hidden"><div className="p-4 border-b"><h2 className="font-bold">Assigned tasks</h2></div><div className="divide-y max-h-96 overflow-auto">{tasks.map(task=><div key={task.id} className="p-4"><div className="flex justify-between"><div><b className="text-sm">{task.title}</b><p className="text-[10px] text-[#6f797c]">{task.project?.name||'General'} · {task.priority}</p></div><select value={task.status} onChange={e=>updateTask(task.id,e.target.value)} className="border rounded px-2 text-xs"><option>OPEN</option><option>IN_PROGRESS</option><option>BLOCKED</option><option>DONE</option></select></div></div>)}{tasks.length===0&&<p className="p-6 text-xs text-[#6f797c]">No tasks assigned.</p>}</div></section>
 <section className="kr-card p-5"><h2 className="font-bold mb-1">Request missing/offline time</h2><p className="text-xs text-[#6f797c] mb-4">Meetings, calls or work completed away from the computer require admin approval.</p>{message&&<p className="text-xs font-bold text-[#005766] mb-3">{message}</p>}<form onSubmit={submit} className="space-y-3"><div className="grid grid-cols-2 gap-2"><input required type="datetime-local" value={startAt} onChange={e=>setStartAt(e.target.value)} className="border rounded-lg px-3 py-2 text-xs"/><input required type="datetime-local" value={endAt} onChange={e=>setEndAt(e.target.value)} className="border rounded-lg px-3 py-2 text-xs"/></div><select value={taskId} onChange={e=>setTaskId(e.target.value)} className="w-full border rounded-lg px-3 py-2 text-xs"><option value="">General work</option>{tasks.map(task=><option key={task.id} value={task.id}>{task.title}</option>)}</select><textarea required minLength={3} value={note} onChange={e=>setNote(e.target.value)} placeholder="What work was completed?" className="w-full border rounded-lg px-3 py-2 text-xs h-24"/><button className="kr-btn-primary text-xs">Submit request</button></form></section></div>
 <section className="kr-card overflow-hidden"><div className="p-4 border-b"><h2 className="font-bold">Recent manual time requests</h2></div><div className="divide-y">{requests.slice(0,10).map(item=><div key={item.id} className="p-4 text-xs flex justify-between"><div><b>{new Date(item.startAt).toLocaleString()} — {new Date(item.endAt).toLocaleTimeString()}</b><p className="text-[#6f797c]">{item.note}</p></div><span className={`kr-badge ${item.status==='APPROVED'?'kr-badge-working':item.status==='REJECTED'?'kr-badge-offline':'kr-badge-idle'}`}>{item.status}</span></div>)}{requests.length===0&&<p className="p-6 text-xs text-[#6f797c]">No manual requests.</p>}</div></section>
 </div></main>;
}
