'use client';

import { FormEvent, useCallback, useEffect, useState } from 'react';

type Employee={id:string;name:string;email:string}; type Project={id:string;name:string};
type Task={id:string;title:string;description:string|null;status:string;priority:string;project:{id:string;name:string}|null;assignedUser:{id:string;name:string}|null};
type Request={id:string;status:string;startAt:string;endAt:string;note:string;user:{name:string;email:string};task:{title:string}|null};
type Alert={id:string;type:string;severity:string;message:string;createdAt:string;readAt:string|null;user:{name:string}|null};

export default function TasksPage(){
 const [data,setData]=useState<{tasks:Task[];employees:Employee[];projects:Project[];requests:Request[];alerts:Alert[]}>({tasks:[],employees:[],projects:[],requests:[],alerts:[]});
 const [title,setTitle]=useState('');const [projectId,setProjectId]=useState('');const [assignedUserId,setAssignedUserId]=useState('');const [priority,setPriority]=useState('NORMAL');
 const load=useCallback(async()=>{const response=await fetch('/api/admin/operations',{cache:'no-store'});const json=await response.json();if(response.ok)setData({tasks:json.tasks||[],employees:json.employees||[],projects:json.projects||[],requests:json.requests||[],alerts:json.alerts||[]});},[]);
 useEffect(()=>{load();const timer=setInterval(load,30000);return()=>clearInterval(timer);},[load]);
 const action=async(payload:Record<string,unknown>)=>{await fetch('/api/admin/operations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});await load();};
 const create=async(event:FormEvent)=>{event.preventDefault();await action({action:'CREATE_TASK',title,projectId,assignedUserId,priority});setTitle('');};
 const pending=data.requests.filter((item)=>item.status==='PENDING'); const unread=data.alerts.filter((item)=>!item.readAt);
 return <div className="space-y-6">
  <div><h1 className="text-xl font-bold text-[#041f24]">Tasks, Approvals & Alerts</h1><p className="text-xs text-[#6f797c] mt-0.5">Assign real tasks, approve offline work, and review automatic exceptions</p></div>
  <div className="grid grid-cols-3 gap-4">{[['Open tasks',data.tasks.filter(t=>!['DONE','ARCHIVED'].includes(t.status)).length],['Manual approvals',pending.length],['Unread alerts',unread.length]].map(([label,value])=><div key={String(label)} className="kr-card p-5"><span className="text-xs uppercase text-[#6f797c] font-semibold">{label}</span><p className="text-2xl font-extrabold text-[#005766] mt-1">{value}</p></div>)}</div>
  <form onSubmit={create} className="kr-card p-4 grid md:grid-cols-5 gap-3"><input required minLength={2} value={title} onChange={(e)=>setTitle(e.target.value)} placeholder="Task title" className="border rounded-lg px-3 py-2 text-xs md:col-span-2"/><select value={projectId} onChange={(e)=>setProjectId(e.target.value)} className="border rounded-lg px-2 text-xs"><option value="">No project</option>{data.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select value={assignedUserId} onChange={(e)=>setAssignedUserId(e.target.value)} className="border rounded-lg px-2 text-xs"><option value="">Anyone</option>{data.employees.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select><div className="flex gap-2"><select value={priority} onChange={(e)=>setPriority(e.target.value)} className="border rounded-lg px-2 text-xs flex-1"><option>NORMAL</option><option>HIGH</option><option>URGENT</option><option>LOW</option></select><button className="kr-btn-primary text-xs">Add</button></div></form>
  <div className="grid xl:grid-cols-2 gap-5"><div className="kr-card overflow-hidden"><div className="p-4 border-b font-bold">Assigned tasks</div><div className="divide-y max-h-[560px] overflow-auto">{data.tasks.map(task=><div key={task.id} className="p-4"><div className="flex justify-between gap-3"><div><b className="text-sm">{task.title}</b><p className="text-[10px] text-[#6f797c]">{task.project?.name||'No project'} · {task.assignedUser?.name||'Unassigned'} · {task.priority}</p></div><select value={task.status} onChange={(e)=>action({action:'UPDATE_TASK',id:task.id,status:e.target.value})} className="border rounded px-2 text-[11px]"><option>OPEN</option><option>IN_PROGRESS</option><option>BLOCKED</option><option>DONE</option><option>ARCHIVED</option></select></div></div>)}{data.tasks.length===0&&<p className="p-6 text-xs text-[#6f797c]">No tasks yet.</p>}</div></div>
  <div className="space-y-5"><div className="kr-card overflow-hidden"><div className="p-4 border-b font-bold">Manual time approvals</div><div className="divide-y max-h-64 overflow-auto">{pending.map(item=><div key={item.id} className="p-4 text-xs"><b>{item.user.name}</b><p className="text-[#6f797c] my-1">{new Date(item.startAt).toLocaleString()} — {new Date(item.endAt).toLocaleTimeString()} · {item.task?.title||'General work'}</p><p className="mb-2">{item.note}</p><div className="flex gap-2"><button onClick={()=>action({action:'REVIEW_MANUAL_TIME',id:item.id,status:'APPROVED'})} className="kr-btn-primary text-[11px]">Approve</button><button onClick={()=>action({action:'REVIEW_MANUAL_TIME',id:item.id,status:'REJECTED'})} className="kr-btn-secondary text-[11px]">Reject</button></div></div>)}{pending.length===0&&<p className="p-6 text-xs text-[#6f797c]">No pending requests.</p>}</div></div>
  <div className="kr-card overflow-hidden"><div className="p-4 border-b font-bold">Smart alerts</div><div className="divide-y max-h-64 overflow-auto">{unread.map(item=><button key={item.id} onClick={()=>action({action:'MARK_ALERT_READ',id:item.id})} className="p-4 w-full text-left hover:bg-[#f0fbff]"><div className="flex justify-between"><b className="text-xs">{item.type.replaceAll('_',' ')}</b><span className="text-[10px] text-[#6f797c]">{new Date(item.createdAt).toLocaleString()}</span></div><p className="text-xs mt-1">{item.message}</p></button>)}{unread.length===0&&<p className="p-6 text-xs text-[#6f797c]">No unread alerts.</p>}</div></div></div></div>
 </div>;
}
